In [92]:
import pandas as pd
titanic_data = pd.read_csv('titanic.csv')

In [93]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [94]:
mask = titanic_data.Fare >= 100
fare_100 = titanic_data[mask]
fare_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

In [95]:
female_fare_100 = fare_100[fare_100.Sex == 'female ']

In [96]:
female_fare_100.shape

(0, 12)

In [97]:
# Female Survival Rate

survived_female = titanic_data[
    (titanic_data.Sex == 'female') & (titanic_data.Survived == 1)
]
survived_female.shape

(233, 12)

In [98]:
# Female Survival Rate

survived_female = titanic_data[
    (titanic_data.Pclass == 1) & (titanic_data.Survived == 1)
]
survived_female.shape

(136, 12)

In [99]:
# Female Survival Rate

survived_female = titanic_data[
    (titanic_data.Pclass == 2) & (titanic_data.Survived == 1)
]
survived_female.shape

(87, 12)

In [100]:
# Female Survival Rate

survived_female = titanic_data[
    (titanic_data.Pclass == 3) & (titanic_data.Survived == 1)
]
survived_female.shape

(119, 12)

In [101]:
titanic_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [102]:
for i in [1, 2, 3]:
    temp = titanic_data[
        (titanic_data.Pclass == i) & (titanic_data.Survived == 1)
    ]
    print(f"Survival rate for class {i}: {temp.shape[0]}")

Survival rate for class 1: 136
Survival rate for class 2: 87
Survival rate for class 3: 119

In [103]:
# isna or notna

null_cabin = titanic_data[titanic_data.Cabin.isna()]
null_cabin.shape

(687, 12)

In [104]:
# duplicated
duplicate_name = titanic_data[titanic_data.Name.duplicated()]
duplicate_name.shape

(0, 12)

In [105]:
# duplicated
duplicate_ticket = titanic_data[titanic_data.Ticket.duplicated()]
duplicate_ticket.shape

(210, 12)

In [106]:
titanic_data[titanic_data.Ticket == '349909']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.075,NaN,S
374,375,0,3,"Palsson, Miss. Stina Viola",female,3.0,3,1,349909,21.075,NaN,S
567,568,0,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,349909,21.075,NaN,S

In [107]:
titanic_data.shape

(891, 12)

In [108]:
titanic_data[titanic_data.Name.isin(['Braund, Mr. Owen Harris'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [109]:
titanic_data.at[10, 'Name']

'Sandstrom, Miss. Marguerite Rut'

In [110]:
titanic_data.loc[10, 'Name']

'Sandstrom, Miss. Marguerite Rut'

In [111]:
titanic_data[["Age", "Fare"]].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [112]:
titanic_data.value_counts("Survived")

Survived
0    549
1    342
Name: count, dtype: int64

In [113]:
titanic_data.value_counts("Survived", normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [114]:
titanic_data.Embarked.value_counts(dropna=False)

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [115]:
titanic_data.value_counts("Sex")

Sex
male      577
female    314
Name: count, dtype: int64

In [116]:
titanic_data.Sex.value_counts(dropna=False)

Sex
male      577
female    314
Name: count, dtype: int64

In [117]:
titanic_data[titanic_data.Sex == 'female'].value_counts("Survived")

Survived
1    233
0     81
Name: count, dtype: int64

In [118]:
titanic_data.value_counts(['Embarked', 'Survived'])

Embarked  Survived
S         0           427
          1           217
C         1            93
          0            75
Q         0            47
          1            30
Name: count, dtype: int64

In [119]:
titanic_data[titanic_data.Sex == 'male'].value_counts("Survived")

Survived
0    468
1    109
Name: count, dtype: int64

In [120]:
titanic_data[
    (titanic_data.Embarked == 'S') & (titanic_data.Sex == 'male')
].value_counts("Survived")

Survived
0    364
1     77
Name: count, dtype: int64

In [121]:
pd.crosstab(
    titanic_data.Sex,
    titanic_data.Survived,
    margins=True,
    margins_name="Total"
)

Survived    0    1  Total
Sex
female     81  233    314
male      468  109    577
Total     549  342    891

In [123]:
pd.crosstab(
    index = [titanic_data.Embarked, titanic_data.Pclass],
    columns = [titanic_data.Sex, titanic_data.Survived],
    margins = True,
    margins_name = "Total"
)

Sex             female      male      Total
Survived             0    1    0    1
Embarked Pclass
C        1           1   42   25   17    85
         2           0    7    8    2    17
         3           8   15   33   10    66
Q        1           0    1    1    0     2
         2           0    2    1    0     3
         3           9   24   36    3    72
S        1           2   46   51   28   127
         2           6   61   82   15   164
         3          55   33  231   34   353
Total               81  231  468  109   889