In [ ]:
import pandas as pd
titanic_df = pd.read_csv('titanic.csv')

In [4]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [5]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
# Get unique values in columns
unique_values = titanic_df.Embarked.unique()
unique_values

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [ ]:
# sum(), prod(), mean(), median(), min(), max(), std(), var() , quantile(), describe()

titanic_df.Age.mean()
titanic_df.Age.median()
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
titanic_df.Age.quantile(q = 0.75)

np.float64(38.0)

In [10]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
titanic_df.Name.describe()

count                         891
unique                        891
top       Braund, Mr. Owen Harris
freq                            1
Name: Name, dtype: object

In [14]:
group_by_gender = titanic_df.groupby(by = 'Sex')

In [15]:
group_by_gender.Fare.sum()

Sex
female    13966.6628
male      14727.2865
Name: Fare, dtype: float64

In [18]:
group_by_gender.value_counts(['Survived'])

Sex     Survived
female  1           233
        0            81
male    0           468
        1           109
Name: count, dtype: int64

In [19]:
res = group_by_gender.Age.mean()
res

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [ ]:
group_by_gender[["Fare", "Age", "Survived"]].sum()

              Fare       Age  Survived
Sex
female  13966.6628   7286.00       233
male    14727.2865  13919.17       109

In [22]:
group_by_two = titanic_df.groupby(["Embarked", "Survived"])

In [24]:
group_by_two[["Age", "Fare"]].mean()

                         Age       Fare
Embarked Survived
C        0         33.666667  35.443335
         1         28.973671  79.720926
Q        0         30.325000  13.335904
         1         22.500000  13.182227
S        0         30.203966  20.743987
         1         28.113184  39.547081

# Correlation and Covariance

In Python, covariance measures the direction of the linear relationship between two variables, while correlation measures both the direction and the strength in a standardized scale from -1 to 1

In [28]:
titanic_df[["Age", "Fare", "SibSp"]].corr()

            Age      Fare     SibSp
Age    1.000000  0.096067 -0.308247
Fare   0.096067  1.000000  0.159651
SibSp -0.308247  0.159651  1.000000

In [29]:
titanic_df[["Age", "Fare"]].cov()

             Age         Fare
Age   211.019125    73.849030
Fare   73.849030  2469.436846

In [34]:
sampled = titanic_df.sample(n = 10, random_state = 42)
sampled

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
709,710,1,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,NaN,C
439,440,0,2,"Kvillner, Mr. Johan Henrik Johannesson",male,31.0,0,0,C.A. 18723,10.5000,NaN,S
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.0,0,1,248727,33.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C
290,291,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S
300,301,1,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,9234,7.7500,NaN,Q
333,334,0,3,"Vander Planke, Mr. Leo Edmondus",male,16.0,2,0,345764,18.0000,NaN,S
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.0,0,0,367231,7.7500,NaN,Q
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S

In [ ]:
# eval is use to evaluate string as an expression 
# eval() can be dangerous if used with user input, because it can execute arbitrary code.
eval("4-2")

2